create sequence hibernate_sequence start 1 increment 1;
create table aves (id int8 generated by default as identity, cor varchar(255) not null, familia varchar(255) not null, genero varchar(255) not null, habitat varchar(255) not null, nome_ingles varchar(255) not null, nome_latim varchar(255) not null, nome_portugues varchar(255) not null, tamanho int4 not null, primary key (id));
create table avistamento (id int8 generated by default as identity, data date, horario timestamp, local varchar(255), ave_id int8, primary key (id));
create table usuario (id int8 not null, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
alter table if exists avistamento add constraint FK8vcua1s9ltr8m6u93a5bd131s foreign key (ave_id) references aves;
